import "server-only";

/**
 * The fallback chain: every gateway the bot may talk to, in the order it tries them.
 *
 * `BotSetting` holds one credential, which is one expired key away from a bot reciting
 * canned Hinglish behind a panel that looks perfectly healthy. These rows are the answer
 * to that — several keys and base URLs, ordered, each one tried until something answers.
 *
 * Two rules, both inherited from `./settings`:
 *
 *  1. **A credential goes in and never comes back out.** `loadEndpointCredentials` hands
 *     keys to the SDK; `listEndpointStatus` — the only thing the panel calls — answers
 *     with labels, booleans and health, and never a value.
 *  2. **A missing table must not stop the bot.** This table's SQL is run by hand, so
 *     until it has been, every read here answers "no fallbacks" — which is exactly how
 *     the bot behaved before the feature existed.
 */

import { randomUUID } from "node:crypto";
import { prisma } from "../prisma";
import { isSealed, seal, unseal } from "./sealed";
import type { EndpointCreate, EndpointPatch, EndpointStatus } from "./bot-config";

/**
 * The AAD for one row: its own id.
 *
 * Not a constant, unlike `BotSetting`'s. There are many rows here, so a wrapped key
 * lifted out of one and pasted into another would otherwise decrypt perfectly well —
 * quietly swapping the key that gets tried first for one an attacker chose. The id is
 * generated by the app rather than by a `@default` for the same reason: the AAD has to
 * exist before the ciphertext does.
 */
const aadFor = (id: string) => `bot-endpoint:${id}`;

/** Priority first, then age, so equal priorities still have a stable order. */
const ORDER = [{ priority: "asc" as const }, { createdAt: "asc" as const }];

/** One gateway with its key unsealed. Never leaves the server. */
export interface EndpointCredential {
  id: string;
  label: string;
  apiKey: string;
  /** Null means the same base URL the settings row (or the environment) uses. */
  baseUrl: string | null;
  /** Null means the same model. */
  model: string | null;
}

/**
 * Every enabled endpoint that actually has a usable key, in order.
 *
 * A row whose key cannot be decrypted is dropped rather than surfaced — that is what
 * having a chain is for, and `unseal` has already logged it once.
 */
export async function loadEndpointCredentials(): Promise<EndpointCredential[]> {
  try {
    const rows = await prisma.botEndpoint.findMany({
      where: { enabled: true },
      orderBy: ORDER,
    });
    return rows.flatMap((row) => {
      const apiKey = unseal(row, aadFor(row.id));
      if (!apiKey) return [];
      return [{ id: row.id, label: row.label, apiKey, baseUrl: row.baseUrl, model: row.model }];
    });
  } catch {
    console.warn("[bakchod-ai] endpoints unreadable; running on the settings credential");
    return [];
  }
}

/**
 * The list the admin panel renders.
 *
 * Booleans and health, never a value — the same rule as `readBotStatus`, applied to
 * rows this time. The array's order *is* the priority order, so the panel does not need
 * the numbers either.
 */
export async function listEndpointStatus(): Promise<EndpointStatus[]> {
  try {
    const rows = await prisma.botEndpoint.findMany({ orderBy: ORDER });
    return rows.map((row) => ({
      id: row.id,
      label: row.label,
      enabled: row.enabled,
      hasKey: isSealed(row),
      hasBaseUrl: row.baseUrl !== null,
      hasModel: row.model !== null,
      lastOkAt: row.lastOkAt?.toISOString() ?? null,
      lastFailAt: row.lastFailAt?.toISOString() ?? null,
      lastStatus: row.lastStatus,
      lastError: row.lastError,
      failures: row.failures,
    }));
  } catch {
    // No table yet. An empty list is the truth, and it lets the rest of the bot panel
    // render — whereas a 500 here would take the cadence form down with it.
    console.warn("[bakchod-ai] endpoints unreadable");
    return [];
  }
}

/** New rows land at the end of the chain: the working setup keeps going first. */
export async function createEndpoint(input: EndpointCreate): Promise<void> {
  const id = randomUUID();
  const last = await prisma.botEndpoint.findFirst({
    orderBy: { priority: "desc" },
    select: { priority: true },
  });

  await prisma.botEndpoint.create({
    data: {
      id,
      label: input.label,
      priority: (last?.priority ?? -1) + 1,
      ...seal(input.apiKey, aadFor(id)),
      baseUrl: input.baseUrl || null,
      model: input.model || null,
    },
  });
}

/**
 * Rename a row, or take it out of the chain without losing its key. False when there is
 * no such row.
 *
 * Nothing here writes a credential: replacing one is `deleteEndpoint` and
 * `createEndpoint`, for the reason on `EndpointPatchSchema`.
 */
export async function updateEndpoint(id: string, patch: EndpointPatch): Promise<boolean> {
  const data: { label?: string; enabled?: boolean } = {};
  if (patch.label !== undefined) data.label = patch.label;
  if (patch.enabled !== undefined) data.enabled = patch.enabled;

  if (Object.keys(data).length === 0) return true;

  const { count } = await prisma.botEndpoint.updateMany({ where: { id }, data });
  return count > 0;
}

/** False when there is no such row. The ciphertext goes with it. */
export async function deleteEndpoint(id: string): Promise<boolean> {
  const { count } = await prisma.botEndpoint.deleteMany({ where: { id } });
  return count > 0;
}

/**
 * Move one row one place up or down the chain.
 *
 * Renumbers the whole list from the swapped order rather than swapping two numbers.
 * Swapping is wrong the first time it is used: every row starts at the priority it was
 * created with, and two rows that happen to share one would swap to no visible effect.
 */
export async function moveEndpoint(id: string, move: "up" | "down"): Promise<boolean> {
  const rows = await prisma.botEndpoint.findMany({ orderBy: ORDER, select: { id: true } });
  const index = rows.findIndex((row) => row.id === id);
  if (index < 0) return false;

  const other = move === "up" ? index - 1 : index + 1;
  // Already at the end it was asked to move towards. Not an error — the button is
  // simply the last press that could do anything.
  if (other < 0 || other >= rows.length) return true;

  const order = rows.map((row) => row.id);
  [order[index], order[other]] = [order[other], order[index]];

  await prisma.$transaction(
    order.map((rowId, priority) =>
      prisma.botEndpoint.update({ where: { id: rowId }, data: { priority } }),
    ),
  );
  return true;
}

/**
 * How often a working endpoint is stamped.
 *
 * A tick can send four requests through the same gateway, and `lastOkAt` exists to
 * answer "is this thing working" — which one write a minute answers just as well as
 * four writes a second. A local constant rather than an import of `TICK_INTERVAL_MS`,
 * which would be a cycle back through the tick that calls this.
 */
const OK_STAMP_MS = 60_000;

/** Last stamp per row, so the throttle costs nothing when nothing has changed. */
const stampedAt = new Map<string, number>();

/**
 * Note that an endpoint answered.
 *
 * Health writes never throw. Losing a timestamp is a worse panel; a comment that fails
 * to post because the bookkeeping failed is a worse feed.
 */
export async function recordEndpointOk(id: string | null): Promise<void> {
  if (!id) return; // The settings row and the environment have no row to stamp.

  const now = Date.now();
  if (now - (stampedAt.get(id) ?? 0) < OK_STAMP_MS) return;
  stampedAt.set(id, now);

  try {
    await prisma.botEndpoint.update({
      where: { id },
      data: { lastOkAt: new Date(now), failures: 0 },
    });
  } catch {
    console.warn("[bakchod-ai] endpoint health not recorded");
  }
}

/** Note that an endpoint threw, in the only two shapes that cannot carry a URL. */
export async function recordEndpointFailure(id: string | null, err: unknown): Promise<void> {
  if (!id) return;
  stampedAt.delete(id);

  try {
    await prisma.botEndpoint.update({
      where: { id },
      data: {
        lastFailAt: new Date(),
        lastStatus: statusOf(err),
        lastError: classOf(err),
        failures: { increment: 1 },
      },
    });
  } catch {
    console.warn("[bakchod-ai] endpoint health not recorded");
  }
}

/** Read structurally rather than via `instanceof`, to keep the SDK out of this module. */
function statusOf(err: unknown): number | null {
  const status = (err as { status?: unknown } | null)?.status;
  return typeof status === "number" && status >= 100 && status <= 599 ? status : null;
}

/**
 * The error's class name — `AuthenticationError`, `APIConnectionError`.
 *
 * Never its message. An SDK error's message can quote the request URL, and the request
 * URL is the base URL this whole surface is built not to show.
 */
function classOf(err: unknown): string {
  if (!(err instanceof Error)) return typeof err;
  return (err.constructor?.name || err.name || "Error").slice(0, 60);
}
